package com.ricdev.mahjongscorecounter.ui.theme

import androidx.compose.ui.graphics.Color

// Palette drawn from the app icon: jade felt, ivory tiles, red 中, gold-and-navy pen.

// Jade + celadon — light
val JadePrimary = Color(0xFF0F6B4F)
val JadeOnPrimary = Color(0xFFFFFFFF)
val JadePrimaryContainer = Color(0xFFBDEBD3)
val JadeOnPrimaryContainer = Color(0xFF002116)
val JadeSecondary = Color(0xFF4D6358)
val JadeOnSecondary = Color(0xFFFFFFFF)
val JadeSecondaryContainer = Color(0xFFD0E8DA)
val JadeOnSecondaryContainer = Color(0xFF0B2A1E)
val CinnabarTertiary = Color(0xFFA8322D)
val CinnabarOnTertiary = Color(0xFFFFFFFF)
val CinnabarTertiaryContainer = Color(0xFFFFDAD5)
val CinnabarOnTertiaryContainer = Color(0xFF410003)
val CeladonBackground = Color(0xFFEEF2EC)
val CeladonOnBackground = Color(0xFF18201C)
val CeladonSurfaceVariant = Color(0xFFDCE5DD)
val CeladonOnSurfaceVariant = Color(0xFF404943)
val CeladonContainerLowest = Color(0xFFFFFFFF)
val CeladonContainerLow = Color(0xFFF8FAF6)
val CeladonContainer = Color(0xFFE4EBE4)
val CeladonContainerHigh = Color(0xFFF3F6F1)
val CeladonContainerHighest = Color(0xFFDDE5DD)
val CeladonOutline = Color(0xFF6F7A72)
val CeladonOutlineVariant = Color(0xFFC2CCC4)

// Jade + celadon — dark
val JadePrimaryDark = Color(0xFF84D7B0)
val JadeOnPrimaryDark = Color(0xFF003825)
val JadePrimaryContainerDark = Color(0xFF005139)
val JadeOnPrimaryContainerDark = Color(0xFFA0F4CB)
val JadeSecondaryDark = Color(0xFFB4CCBE)
val JadeOnSecondaryDark = Color(0xFF1F352A)
val JadeSecondaryContainerDark = Color(0xFF24463A)
val JadeOnSecondaryContainerDark = Color(0xFFCFE9DA)
val CinnabarTertiaryDark = Color(0xFFFFB4A9)
val CinnabarOnTertiaryDark = Color(0xFF690005)
val CinnabarTertiaryContainerDark = Color(0xFF8C1D18)
val CinnabarOnTertiaryContainerDark = Color(0xFFFFDAD5)
val CeladonBackgroundDark = Color(0xFF0E1512)
val CeladonOnBackgroundDark = Color(0xFFDEE4DF)
val CeladonSurfaceVariantDark = Color(0xFF3F4943)
val CeladonOnSurfaceVariantDark = Color(0xFFBFC9C1)
val CeladonContainerLowestDark = Color(0xFF09100D)
val CeladonContainerLowDark = Color(0xFF151D19)
val CeladonContainerDark = Color(0xFF19221E)
val CeladonContainerHighDark = Color(0xFF222C27)
val CeladonContainerHighestDark = Color(0xFF2C3631)
val CeladonOutlineDark = Color(0xFF89938C)
val CeladonOutlineVariantDark = Color(0xFF3F4943)

// Table materials
val Felt = Color(0xFF145C42)
val FeltLit = Color(0xFF1B7253)
val FeltRim = Color(0xFF0B2C22)
val FeltDark = Color(0xFF0F3F2F)
val FeltLitDark = Color(0xFF155039)
val FeltRimDark = Color(0xFF1C352B)
val GoldInlay = Color(0xFFC9A44C)
val GoldInlayDark = Color(0xFFA08236)
val GoldRing = Color(0xFFE3B341)

// Tile materials
val TileIvory = Color(0xFFFBF6E8)
val TileIvoryShade = Color(0xFFEDE3CB)
val TileIvoryDark = Color(0xFFECE4CF)
val TileIvoryShadeDark = Color(0xFFD6CBAF)
val TileJadeBack = Color(0xFF23946B)
val TileJadeBackShade = Color(0xFF16704F)
val TileJadeBackDark = Color(0xFF1E7A59)
val TileJadeBackShadeDark = Color(0xFF135A41)
val TileInk = Color(0xFF1C2A4A)
val DragonRed = Color(0xFFC0322B)

// Delta colors on app surfaces
val DeltaPositive = Color(0xFF13734F)
val DeltaNegative = Color(0xFFB3261E)
val DeltaNeutral = Color(0xFF5C6660)
val DeltaPositiveDark = Color(0xFF7DDAA9)
val DeltaNegativeDark = Color(0xFFFFB4AB)
val DeltaNeutralDark = Color(0xFFBFC9C1)

// Delta colors on ivory tile faces (always light, in both themes)
val TileDeltaPositive = Color(0xFF0F6B4F)
val TileDeltaNegative = Color(0xFFB02A24)
